; Generated by LCG csv_to_bend_gcode.py
; Feed wire, bend, and rotate to create 3D sculpture
G28 ; Home all axes

G1 F7.06 ; Feed 7.06mm
G2 B77.9 ; Bend 77.9 degrees
G1 F3.23 ; Feed 3.23mm
G2 B58.9 ; Bend 58.9 degrees
G1 F3.47 ; Feed 3.47mm
G2 B-61.5 ; Bend -61.5 degrees
G1 F6.10 ; Feed 6.10mm
G2 B-151.0 ; Bend -151.0 degrees
G1 F2.23 ; Feed 2.23mm
G2 B24.7 ; Bend 24.7 degrees
G1 F9.03 ; Feed 9.03mm
G2 B-90.7 ; Bend -90.7 degrees
G1 F9.19 ; Feed 9.19mm
G2 B27.0 ; Bend 27.0 degrees
G1 F2.16 ; Feed 2.16mm
G1 F2.85 ; Feed 2.85mm
G2 B24.2 ; Bend 24.2 degrees
G1 F3.33 ; Feed 3.33mm
G2 B60.5 ; Bend 60.5 degrees
G1 F3.33 ; Feed 3.33mm
G2 B-64.5 ; Bend -64.5 degrees
G1 F3.41 ; Feed 3.41mm
G2 B-94.3 ; Bend -94.3 degrees
G1 F2.36 ; Feed 2.36mm
G2 B13.1 ; Bend 13.1 degrees
G1 F4.47 ; Feed 4.47mm
G2 B-82.1 ; Bend -82.1 degrees
G1 F4.35 ; Feed 4.35mm
G2 B12.6 ; Bend 12.6 degrees
G1 F2.39 ; Feed 2.39mm
G2 B16.4 ; Bend 16.4 degrees
G1 F3.21 ; Feed 3.21mm
G2 B25.9 ; Bend 25.9 degrees
G1 F2.18 ; Feed 2.18mm
G2 B16.9 ; Bend 16.9 degrees
G1 F3.55 ; Feed 3.55mm
G2 B-55.2 ; Bend -55.2 degrees
G1 F3.88 ; Feed 3.88mm
G2 B-64.2 ; Bend -64.2 degrees
G1 F3.48 ; Feed 3.48mm
G2 B33.1 ; Bend 33.1 degrees
G1 F2.89 ; Feed 2.89mm
G2 B7.6 ; Bend 7.6 degrees
G1 F2.67 ; Feed 2.67mm
G2 B23.7 ; Bend 23.7 degrees
G1 F4.92 ; Feed 4.92mm
G2 B-135.4 ; Bend -135.4 degrees
G1 F2.39 ; Feed 2.39mm
G2 B23.3 ; Bend 23.3 degrees
G1 F2.03 ; Feed 2.03mm
G2 B-61.9 ; Bend -61.9 degrees
G1 F6.90 ; Feed 6.90mm
G2 B67.9 ; Bend 67.9 degrees
G1 F7.01 ; Feed 7.01mm
G2 B-134.5 ; Bend -134.5 degrees
G1 F2.72 ; Feed 2.72mm
G2 B17.5 ; Bend 17.5 degrees
G1 F2.74 ; Feed 2.74mm
G2 B-82.7 ; Bend -82.7 degrees
G1 F3.14 ; Feed 3.14mm
G2 B31.5 ; Bend 31.5 degrees
G1 F2.09 ; Feed 2.09mm
G2 B17.2 ; Bend 17.2 degrees
G1 F3.92 ; Feed 3.92mm
G2 B-35.2 ; Bend -35.2 degrees
G1 F4.02 ; Feed 4.02mm
G2 B14.4 ; Bend 14.4 degrees
G1 F2.32 ; Feed 2.32mm
G2 B17.1 ; Bend 17.1 degrees
G1 F3.20 ; Feed 3.20mm
G2 B-16.3 ; Bend -16.3 degrees
G1 F2.68 ; Feed 2.68mm
G2 B8.0 ; Bend 8.0 degrees
G1 F2.43 ; Feed 2.43mm
G2 B27.8 ; Bend 27.8 degrees
G1 F2.18 ; Feed 2.18mm
G2 B19.2 ; Bend 19.2 degrees
G1 F5.68 ; Feed 5.68mm
G2 B-49.1 ; Bend -49.1 degrees
G1 F8.31 ; Feed 8.31mm
G2 B26.6 ; Bend 26.6 degrees
G1 F2.45 ; Feed 2.45mm
G2 B20.9 ; Bend 20.9 degrees
G1 F10.48 ; Feed 10.48mm
G2 B-45.3 ; Bend -45.3 degrees
G1 F15.55 ; Feed 15.55mm
G2 B54.5 ; Bend 54.5 degrees
G1 F2.13 ; Feed 2.13mm
G2 B89.3 ; Bend 89.3 degrees

; --- SCULPTURE COMPLETE ---
; Total wire used: 190.1mm (0.19m)
; Total bends: 44
M2 ; End program