"""
csv_to_bend_gcode.py

Converts a 3D weaving path (from the Sweetgrass Slicer) into G-code for a CNC Wire Bender.
The output is optimized for the jpraus/wirebender or kavers1/wirebender firmware.

Wire Bending G-Code Commands (Custom):
  G1 Fnn     - Feed nn millimeters of wire
  G2 Bnn     - Bend nn degrees (positive = clockwise)
  G3 Znn     - Rotate Z-axis nn degrees (for 3D forms)
"""

import numpy as np
import math

def calculate_bend_angle(p1, p2, p3):
    """
    Calculate the bend angle at point p2 given three consecutive points.
    Returns the angle in degrees.
    """
    v1 = np.array(p2) - np.array(p1)
    v2 = np.array(p3) - np.array(p2)
    
    # Normalize
    v1_norm = v1 / (np.linalg.norm(v1) + 1e-9)
    v2_norm = v2 / (np.linalg.norm(v2) + 1e-9)
    
    # Dot product for angle
    dot = np.clip(np.dot(v1_norm, v2_norm), -1.0, 1.0)
    angle_rad = math.acos(dot)
    angle_deg = math.degrees(angle_rad)
    
    # Cross product for direction (sign)
    cross = np.cross(v1_norm[:2], v2_norm[:2])  # Use XY plane for 2D sign
    if cross < 0:
        angle_deg = -angle_deg
    
    return angle_deg

def csv_to_bend_gcode(input_csv, output_gcode, min_segment_mm=2.0, min_bend_deg=3.0):
    """
    Main converter function.
    
    Args:
        input_csv: Path to the bear_path.csv or similar file.
        output_gcode: Path to write the output .gcode file.
        min_segment_mm: Minimum segment length to include (filters noise).
        min_bend_deg: Minimum bend angle to emit a bend command.
    """
    print(f"Loading path from {input_csv}...")
    data = np.loadtxt(input_csv, delimiter=",", skiprows=1)
    
    # Handle 4-column data (x, y, z, material_id)
    if data.shape[1] > 3:
        path = data[:, :3]
    else:
        path = data
    
    print(f"Loaded {len(path)} points. Processing...")
    
    gcode = []
    gcode.append("; Generated by LCG csv_to_bend_gcode.py")
    gcode.append("; Feed wire, bend, and rotate to create 3D sculpture")
    gcode.append("G28 ; Home all axes")
    gcode.append("")
    
    total_wire_mm = 0
    total_bends = 0
    
    for i in range(1, len(path) - 1):
        p1 = path[i - 1]
        p2 = path[i]
        p3 = path[i + 1]
        
        # Calculate feed distance (length of segment from p1 to p2)
        segment_length = np.linalg.norm(p2 - p1)
        
        if segment_length < min_segment_mm:
            continue  # Skip very short segments
        
        # Feed the wire
        gcode.append(f"G1 F{segment_length:.2f} ; Feed {segment_length:.2f}mm")
        total_wire_mm += segment_length
        
        # Calculate bend angle
        bend_angle = calculate_bend_angle(p1, p2, p3)
        
        if abs(bend_angle) >= min_bend_deg:
            gcode.append(f"G2 B{bend_angle:.1f} ; Bend {bend_angle:.1f} degrees")
            total_bends += 1
        
        # Calculate Z rotation (for 3D)
        # This is a simplified version - just tracks Z height change
        z_change = p3[2] - p2[2]
        if abs(z_change) > 0.5:
            z_angle = math.degrees(math.atan2(z_change, segment_length))
            gcode.append(f"G3 Z{z_angle:.1f} ; Z-rotate {z_angle:.1f} degrees")
    
    # Handle the last segment
    last_segment = np.linalg.norm(path[-1] - path[-2])
    if last_segment >= min_segment_mm:
        gcode.append(f"G1 F{last_segment:.2f} ; Feed final {last_segment:.2f}mm")
        total_wire_mm += last_segment
    
    gcode.append("")
    gcode.append("; --- SCULPTURE COMPLETE ---")
    gcode.append(f"; Total wire used: {total_wire_mm:.1f}mm ({total_wire_mm/1000:.2f}m)")
    gcode.append(f"; Total bends: {total_bends}")
    gcode.append("M2 ; End program")
    
    # Write to file
    with open(output_gcode, 'w') as f:
        f.write("\n".join(gcode))
    
    print(f"\n=== WIRE BENDER G-CODE GENERATED ===")
    print(f"Output file: {output_gcode}")
    print(f"Total wire needed: {total_wire_mm:.1f}mm ({total_wire_mm/1000:.2f} meters)")
    print(f"Total bend operations: {total_bends}")
    print(f"Total G-code commands: {len(gcode)}")

if __name__ == "__main__":
    csv_to_bend_gcode(
        "bear_path.csv", 
        "bear_wire_sculpture.gcode",
        min_segment_mm=2.0,
        min_bend_deg=5.0
    )
